module ModuleWithException

def funcWithException(){
	1;
	2;
	throw 'qwqwqwq'
	return 3;
}
